const types = {

    LOADING: "LOADING",
    FAIL: "FAIL",
    SUCCESS: "SUCCESS",

    CATEGORI: "CATEGORI",
    POST: "POST",
    PHARMACY: "PHARMACY",
    DETAIL_PHARMACY: "DETAIL_PHARMACY",
    LOCATION: "LOCATION",
    RESULT_PHARMACY: "RESULT_PHARMACY",
    LOGIN:"LOGIN",
    DETAIL_POST:"DETAIL_POST"
}

export default types;